import {ItemType} from "../components/MySelect/MySelect";


export const provinceItems: ItemType[] = [
    { value: 'Alborz', title: 'البرز' },
    { value: 'Ardabil', title: 'اردبیل' },
    { value: 'Isfahan', title: 'اصفهان' },
    { value: 'East Azerbaijan', title: 'آذربایجان شرقی' },
    { value: 'West Azerbaijan', title: 'آذربایجان غربی' },
    { value: 'Ilam', title: 'ایلام' },
    { value: 'Bushehr', title: 'بوشهر' },
    { value: 'Tehran', title: 'تهران' },
    { value: 'Chaharmahal and Bakhtiari', title: 'چهارمحال و بختیاری' },
    { value: 'South Khorasan', title: 'خراسان جنوبی' },
    { value: 'Razavi Khorasan', title: 'خراسان رضوی' },
    { value: 'North Khorasan', title: 'خراسان شمالی' },
    { value: 'Khuzestan', title: 'خوزستان' },
    { value: 'Zanjan', title: 'زنجان' },
    { value: 'Semnan', title: 'سمنان' },
    { value: 'Sistan and Baluchestan', title: 'سیستان و بلوچستان' },
    { value: 'Fars', title: 'فارس' },
    { value: 'Qazvin', title: 'قزوین' },
    { value: 'Qom', title: 'قم' },
    { value: 'Kurdistan', title: 'کردستان' },
    { value: 'Kerman', title: 'کرمان' },
    { value: 'Kermanshah', title: 'کرمانشاه' },
    { value: 'Kohgiluyeh and Boyer-Ahmad', title: 'کهگیلویه و بویراحمد' },
    { value: 'Golestan', title: 'گلستان' },
    { value: 'Gilan', title: 'گیلان' },
    { value: 'Lorestan', title: 'لرستان' },
    { value: 'Mazandaran', title: 'مازندران' },
    { value: 'Markazi', title: 'مرکزی' },
    { value: 'Hormozgan', title: 'هرمزگان' },
    { value: 'Hamedan', title: 'همدان' },
    { value: 'Yazd', title: 'یزد' },
];