import { MRT_PaginationState } from "material-react-table";
import { Dispatch, RefObject, SetStateAction } from "react";

export interface DataTableProps {
  keyName?: string;
  tableInstanceRef?: RefObject<any>;
  columns: any;
  data: any;
  isFetching?: boolean;
  pagination?: MRT_PaginationState;
  setPagination?: Dispatch<SetStateAction<MRT_PaginationState>>;
  totalCount?: number;
  globalSearch?: boolean;
  disableTopToolbar?: boolean;
  disableToolbar?: boolean;
  noAlertBanner?: boolean;
  disableRowSelection?: boolean;
  disablePagination?: boolean;
  enableRowVirtual?: boolean;
  selectedRows?: any;
  onRowClicked?: (arg: any) => void;
  refetchTable?: () => void;
  hasContextMenu?: boolean;
  deleteRows?: () => void;
  viewRows?: () => void;
  reViewRows?: () => void;
  hasRowAction?: boolean;
  showRowDetail?: (row: any) => void;
  attachments?: (row: any) => void;
  editRow?: (row: any) => void;
  rowSelfTests?: (row: any) => void;
  rowServices?: (row: any) => void;
  deleteRow?: (row: any) => void;
  resetPassword?: (row: any) => void;
  showGraph?: (row: any) => void;
  enableEntity?: (row: any) => void;
  checkValidIp?: (row: any) => void;
  goToValidIps?: (row: any) => void;
  goToSmsBulk?: (row: any) => void;
  columnVisibility?: any;
  setColumnVisibility?: any;
  totalFetched?: number;
  isLoading?: boolean;
  globalFilter?: string;
  setGlobalFilter?: (args: any) => any;
  fetchNextPage?: () => any;
  hasOtp?: boolean;
  exportAll?: (format: string) => void;
  columnFilters?: any;
  sorting?: any;
  remoteFilter?: any;
  remoteSorting?: any;
}
