sonar.projectKey=sata-frontend
sonar.version=1
sonar.sources=src
sonar.host.url=http://10.17.52.59
sonar.login=squ_b14e842d878be159eb30e2584f7be3be339352e9
sonar.scm.enabled=true
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.exclusions=**/*.test.*, **/constants.ts, **/theme.tsx, **/mock/server/api/dashboard/ttp/ttpDashboard.ts, **/Dashboard/Threat/API/ThreatActorMostRoles.tsx